import { environment } from '../../../environments/environment';
import { HttpHeaders } from '@angular/common/http';

export class HttpService {

    static SERVICE_PATH = 'http://localhost:8080/';
    static AUTH_SERVICE_CONTEXT_URL = `${HttpService.SERVICE_PATH}auth_service/api/v1/`;
    static AUTH_SERVICE_CONTEXT_URL_AUTH = `${HttpService.AUTH_SERVICE_CONTEXT_URL}auth/`;
    // static AUTH_SERVICE_CONTEXT_URL_ROLE: =
    // static AUTH_SERVICE_CONTEXT_URL_PRIVILEGE: =

    /*BANK MODULE APIS START*/
    static BANK_SAVE_PAYMENT = environment.ADMIN_SERVICE.BANK.SAVE_PAYMENT;
    static BANK_SELECTED_DEPOSITE = environment.ADMIN_SERVICE.BANK.SELECTED_DEPOSITE;
    static BANK_SELECTED_SPEND_MONEY = environment.ADMIN_SERVICE.BANK.SELECTED_SPEND_MONEY;
    static BANK_CANCEL_SPEND_MONEY = environment.ADMIN_SERVICE.BANK.CANCEL_SPEND_MONEY;
    static BANK_CANCEL_REQUEST_MONEY = environment.ADMIN_SERVICE.BANK.CANCEL_REQUEST_MONEY;
    static BANK_SAVE_RECEIVED_MONEY = environment.ADMIN_SERVICE.BANK.SAVE_RECEIVED_MONEY;
    static BANK_GET_SPEND_MONEY_TABLE = environment.ADMIN_SERVICE.BANK.GET_SPEND_MONEY_TABLE;
    static BANK_GET_RECEIVED_MONEY_TABLE = environment.ADMIN_SERVICE.BANK.GET_RECEIVED_MONEY_TABLE;

    static BANK_GET_FIXED_DEPOSITE_TABLE = environment.ADMIN_SERVICE.BANK.GET_FIXED_DEPOSITE_TABLE_DATA;

    static BANK_GET_LOAN_DETAIL_TABLE = environment.ADMIN_SERVICE.BANK.GET_LOAN_DETAILS_TABLE_DATA;
    /*BANK MODULE APIS END*/



    /*COMPANY MODULE APIS START*/
    static COMPANY_GET_CHART_OF_ACCOUNT_DATA = environment.ADMIN_SERVICE.COMPANY.GET_CHART_OF_ACCOUNT_TABLE_DATA;
    static COMPANY_SAVE_DETAIL_COA = environment.ADMIN_SERVICE.COMPANY.SAVE_DETAIL_COA;
    static COMPANY_SAVE_HEADER_COA = environment.ADMIN_SERVICE.COMPANY.SAVE_HEADER_COA;
    static COMPANY_LOAD_OTHER_SUB_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_OTHER_SUB_ACCOUNT;
    static COMPANY_LOAD_HEADER_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_HEADER_ACCOUNT;
    static COMPANY_OTHER_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_OTHER_ACCOUNT;

    static COMPANY_ENTRY_AUTHORIZATION = environment.ADMIN_SERVICE.COMPANY.ENTRY_AUTHORIZATION;
    static COMPANY_LOAD_PENDING_AUTH = environment.ADMIN_SERVICE.COMPANY.LOAD_PENDING_AUTH;
    static COMPANY_LOAD_ALL_ENTRIES = environment.ADMIN_SERVICE.COMPANY.LOAD_All_ENTRIES;

    static COMPANY_LOAD_ALL_JOU = environment.ADMIN_SERVICE.COMPANY.LOAD_All_JOU;
    static COMPANY_SAVE_JOU = environment.ADMIN_SERVICE.COMPANY.SAVE_JOU;
    static COMPANY_LOAD_SELECTED_JOU = environment.ADMIN_SERVICE.COMPANY.LOAD_SELECTED_JOU;
    /*COMPANY MODULE APIS END*/

    /*COMPANY MODULE APIS START*/
    static CUSTOMER_GET_CUS_OB_TABLE_DATA = environment.ADMIN_SERVICE.CUSTOMER.GET_CUS_OB_TABLE_DATA;
    static CUSTOMER_DELETE_CUS_OB_DATA = environment.ADMIN_SERVICE.CUSTOMER.DELETE_SUP_CUS_OB_DATA;
    static CUSTOMER_SAVE_CUS_OB_DATA = environment.ADMIN_SERVICE.CUSTOMER.SAVE_SUP_CUS_OB_DATA;
    static CUSTOMER_LOAD_SELECTED_CUS_OB = environment.ADMIN_SERVICE.CUSTOMER.LOAD_SELECTED_SUP_CUS_OB;
    /*COMPANY MODULE APIS END*/

    /*VENDOR MODULE APIS START*/
    static VENDOR_GET_VEN_TABLE_DATA = environment.ADMIN_SERVICE.VENDOR.GET_VEN_TABLE_DATA;
    static VENDOR_SAVE_VEN_DATA = environment.ADMIN_SERVICE.VENDOR.SAVE_VEN_DATA;
    static VENDOR_SAVE_VEN_OTHER_DATA = environment.ADMIN_SERVICE.VENDOR.SAVE_VEN_OTHER_DATA;
    static VENDOR_LOAD_SELECTED_VEN_DATA = environment.ADMIN_SERVICE.VENDOR.LOAD_SELECTED_VEN_DATA;
    /*VENDOR MODULE APIS END*/

    /*COMMON MODULE APIS START*/
    static COMMON_LOAD_SELECTED_ENTRY = environment.ADMIN_SERVICE.COMMON.LOAD_SELECTED_ENTRY;
    static COMMON_LOAD_CURRENCY = environment.ADMIN_SERVICE.COMMON.LOAD_CURRENCY;
    static COMMON_LOAD_JOU_TYPES = environment.ADMIN_SERVICE.COMMON.LOAD_JOU_TYPES;
    static COMMON_LOAD_LEDGERS = environment.ADMIN_SERVICE.COMMON.LOAD_LEDGERS;
    static COMMON_LOAD_PLANTS = environment.ADMIN_SERVICE.COMMON.LOAD_PLANTS;
    static COMMON_LOAD_SHIPMENTS = environment.ADMIN_SERVICE.COMMON.LOAD_SHIPMENTS;
    static COMMON_LOAD_VENDORS = environment.ADMIN_SERVICE.COMMON.LOAD_VENDORS;
    /*COMMON MODULE APIS END*/


    static getDefaultHeaders(): HttpHeaders {
        const token = sessionStorage.getItem('accessToken');
        let headers = new HttpHeaders({
            'Content-Type': 'application/json',
            'Authorization': 'Bearer '+token!
        });
        return headers;
    }
}
