import { Injectable } from '@angular/core';
import {environment} from "../environments/environment";
import {HttpHeaders} from "@angular/common/http";

@Injectable({
  providedIn: 'root'
})
export class HttpService {
  static SERVICE_PATH = environment.apiUrl;

  /*BANK MODULE APIS START*/
  static BANK_SAVE_PAYMENT = environment.ADMIN_SERVICE.BANK.SAVE_PAYMENT;
  static BANK_SELECTED_DEPOSITE = environment.ADMIN_SERVICE.BANK.SELECTED_DEPOSITE;
  static BANK_SELECTED_SPEND_MONEY = environment.ADMIN_SERVICE.BANK.SELECTED_SPEND_MONEY;
  static BANK_CANCEL_SPEND_MONEY = environment.ADMIN_SERVICE.BANK.CANCEL_SPEND_MONEY;
  static BANK_CANCEL_REQUEST_MONEY = environment.ADMIN_SERVICE.BANK.CANCEL_REQUEST_MONEY;
  static BANK_SAVE_RECEIVED_MONEY = environment.ADMIN_SERVICE.BANK.SAVE_RECEIVED_MONEY;
  static BANK_GET_SPEND_MONEY_TABLE = environment.ADMIN_SERVICE.BANK.GET_SPEND_MONEY_TABLE;
  static BANK_GET_RECEIVED_MONEY_TABLE = environment.ADMIN_SERVICE.BANK.GET_RECEIVED_MONEY_TABLE;

  static BANK_GET_FIXED_DEPOSITE_TABLE = environment.ADMIN_SERVICE.BANK.GET_FIXED_DEPOSITE_TABLE_DATA;

  static BANK_GET_LOAN_DETAIL_TABLE = environment.ADMIN_SERVICE.BANK.GET_LOAN_DETAILS_TABLE_DATA;
  static BANK_GET_LOAN_DETAIL_TABLE_NOT_FD = environment.ADMIN_SERVICE.BANK.GET_LOAN_DETAILS_TABLE_DATA_NOT_FD;
  static BANK_LOAN_SAVE = environment.ADMIN_SERVICE.BANK.API_BANK_LOAN_SAVE;
  static BANK_LOAN_NOT_FD_SAVE = environment.ADMIN_SERVICE.BANK.API_BANK_LOAN_NOT_FD_SAVE;
  static BANK_GET_LOAN_TYPES = environment.ADMIN_SERVICE.BANK.API_BANK_GET_LOAN_TYPES;
  static BANK_LOAD_SELECTED_FD = environment.ADMIN_SERVICE.BANK.API_BANK_LOAD_SELECTED_FD;
  static BANK_LOAD_SELECTED_LOAN = environment.ADMIN_SERVICE.BANK.API_BANK_LOAD_SELECTED_LOAN;

  static BANK_PRINT_CHEQUE_MAIN_TABLE = environment.ADMIN_SERVICE.BANK.API_PRINT_CHEQUE_MAIN_TABLE;
  static BANK_UPDATE_PRINT_DETAILS = environment.ADMIN_SERVICE.BANK.API_UPDATE_PRINT_DETAILS;
  static BANK_API_CHECK_PRINT = environment.ADMIN_SERVICE.BANK.API_CHECK_PRINT;

  static BANK_RECONSILATION_MAIN_TABLE = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_MAIN_TABLE;
  static BANK_RECONSILATION_SELECTED = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_SELECTED;
  static BANK_RECONSILATION_SUMMERY_SELECTED = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_SUMMERY_SELECTED;
  static BANK_RECONSILATION_LOAD_BANK_DETAILS = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_LOAD_BANK_DETAILS;
  static BANK_RECONSILATION_LOAD_TRANSACTIONS = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_LOAD_TRANSACTIONS;
  static BANK_RECONSILATION_SAVE_RECONCILE = environment.ADMIN_SERVICE.BANK.API_RECONSILATION_SAVE_RECONCILE;


  /*BANK MODULE APIS END*/



  /*COMPANY MODULE APIS START*/
  static COMPANY_GET_CHART_OF_ACCOUNT_DATA = environment.ADMIN_SERVICE.COMPANY.GET_CHART_OF_ACCOUNT_TABLE_DATA;
  static COMPANY_SAVE_DETAIL_COA = environment.ADMIN_SERVICE.COMPANY.SAVE_DETAIL_COA;
  static COMPANY_SAVE_HEADER_COA = environment.ADMIN_SERVICE.COMPANY.SAVE_HEADER_COA;
  static COMPANY_LOAD_OTHER_SUB_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_OTHER_SUB_ACCOUNT;
  static COMPANY_LOAD_HEADER_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_HEADER_ACCOUNT;
  static COMPANY_OTHER_ACCOUNT = environment.ADMIN_SERVICE.COMPANY.LOAD_OTHER_ACCOUNT;

  static COMPANY_ENTRY_AUTHORIZATION = environment.ADMIN_SERVICE.COMPANY.ENTRY_AUTHORIZATION;
  static COMPANY_LOAD_PENDING_AUTH = environment.ADMIN_SERVICE.COMPANY.LOAD_PENDING_AUTH;
  static COMPANY_LOAD_ALL_ENTRIES = environment.ADMIN_SERVICE.COMPANY.LOAD_All_ENTRIES;

  static COMPANY_LOAD_ALL_JOU = environment.ADMIN_SERVICE.COMPANY.LOAD_All_JOU;
  static COMPANY_SAVE_JOU = environment.ADMIN_SERVICE.COMPANY.SAVE_JOU;
  static COMPANY_LOAD_SELECTED_JOU = environment.ADMIN_SERVICE.COMPANY.LOAD_SELECTED_JOU;
  static COMPANY_GET_FINANCIAL_YEAR_LIST = environment.ADMIN_SERVICE.COMPANY.GET_FINANCIAL_YEAR_LIST;
  static COMPANY_GET_FINANCIAL_YEAR_DETAILS = environment.ADMIN_SERVICE.COMPANY.GET_FINANCIAL_YEAR_DETAILS;
  static COMPANY_CHECK_PENDING_ENTRIES = environment.ADMIN_SERVICE.COMPANY.GET_PENDING_ENTRIES;
  static COMPANY_DATE_CONTROLLER_LOAD_EVENTS = environment.ADMIN_SERVICE.COMPANY.LOAD_EVENTS;
  static COMPANY_DATE_CONTROLLER_UPDATE_CALENDER = environment.ADMIN_SERVICE.COMPANY.UPDATE_CALENDER;
  static COMPANY_DATE_CONTROLLER_ACTIVE_DEACTIVE_DATES = environment.ADMIN_SERVICE.COMPANY.ACTIVE_DEACTIVE_DATES;
  static COMPANY_PREVIEW_LEDGER_BAL = environment.ADMIN_SERVICE.COMPANY.GET_LEDGER_BAL;



  static COMPANY_LOAD_ALL_ITEM = environment.ADMIN_SERVICE.COMPANY.LOAD_ALL_ITEM;
  static COMPANY_LOAD_CATEGORY = environment.ADMIN_SERVICE.COMPANY.LOAD_CATEGORY;
  static COMPANY_LOAD_UOM_FOR_TYPE = environment.ADMIN_SERVICE.COMPANY.LOAD_UOM_FOR_TYPE;
  static COMPANY_LOAD_UOM_LIST = environment.ADMIN_SERVICE.COMPANY.LOAD_UOM_LIST;
  static COMPANY_LOAD_SALES_LEDGER = environment.ADMIN_SERVICE.COMPANY.LOAD_SALES_LEDGER;
  static COMPANY_LOAD_BINS = environment.ADMIN_SERVICE.COMPANY.LOAD_BINS;
  static COMPANY_SAVE_ITEM = environment.ADMIN_SERVICE.COMPANY.SAVE_ITEM;
  static COMPANY_GET_GROUPS = environment.ADMIN_SERVICE.COMPANY.GET_GROUPS;
  static COMPANY_SELECTED_ITEM = environment.ADMIN_SERVICE.COMPANY.SELECTED_ITEM;
  static COMPANY_CATEGORY_LIST = environment.ADMIN_SERVICE.COMPANY.CATEGORY_LIST;
  static COMPANY_UPDATE_CATEGORY = environment.ADMIN_SERVICE.COMPANY.UPDATE_CATEGORY;
  static COMPANY_UPDATE_GROUP = environment.ADMIN_SERVICE.COMPANY.UPDATE_GROUP;
  static COMPANY_DELETE_CATEGORY = environment.ADMIN_SERVICE.COMPANY.DELETE_CATEGORY;
  static COMPANY_DELETE_GROUP = environment.ADMIN_SERVICE.COMPANY.DELETE_GROUP;
  static COMPANY_LIST_CATEGORY = environment.ADMIN_SERVICE.COMPANY.LIST_CATEGORY;
  static COMPANY_LIST_ITEM_GROUPS = environment.ADMIN_SERVICE.COMPANY.LIST_ITEM_GROUPS;
  /*COMPANY MODULE APIS END*/

  /*CUSTOMER MODULE APIS START*/
  static CUSTOMER_GET_CUS_OB_TABLE_DATA = environment.ADMIN_SERVICE.CUSTOMER.GET_CUS_OB_TABLE_DATA;
  static CUSTOMER_DELETE_CUS_OB_DATA = environment.ADMIN_SERVICE.CUSTOMER.DELETE_SUP_CUS_OB_DATA;
  static CUSTOMER_SAVE_CUS_OB_DATA = environment.ADMIN_SERVICE.CUSTOMER.SAVE_SUP_CUS_OB_DATA;
  static CUSTOMER_LOAD_SELECTED_CUS_OB = environment.ADMIN_SERVICE.CUSTOMER.LOAD_SELECTED_SUP_CUS_OB;
  static CUSTOMER_GET_CRN_PRINT_JASPER = environment.ADMIN_SERVICE.CUSTOMER.GET_CRN_PRINT_JASPER;

  static CUSTOMER_LOAD_CUS_MANAGE_DATA = environment.ADMIN_SERVICE.CUSTOMER.LOAD_CUS_MANAGE_DATA;
  static CUSTOMER_SAVE_CUS_MANAGE_DATA = environment.ADMIN_SERVICE.CUSTOMER.SAVE_CUS_MANAGE_DATA;
  static CUSTOMER_SELECTED_CUS_MANAGE_DATA = environment.ADMIN_SERVICE.CUSTOMER.GET_SELECT_CUS_MANAGE_DATA;
  static CUSTOMER_GET_SELECT_DEL_TO = environment.ADMIN_SERVICE.CUSTOMER.GET_SELECT_DEL_TO;
  static CUSTOMER_SAVE_NORTIFY_DETAILS = environment.ADMIN_SERVICE.CUSTOMER.SAVE_NORTIFY_DETAILS;
  static CUSTOMER_DELETE_NORTIFY_DETAILS = environment.ADMIN_SERVICE.CUSTOMER.DELETE_NORTIFY_DETAILS;
  static CUSTOMER_ALL_LOCAL_INVOICES = environment.ADMIN_SERVICE.CUSTOMER.ALL_LOCAL_INVOICES;
  static CUSTOMER_SAVE_INVOICE = environment.ADMIN_SERVICE.CUSTOMER.SAVE_LOCAL_INVOICES;
  static CUSTOMER_LOAD_SELECTED_INVOICE = environment.ADMIN_SERVICE.CUSTOMER.LOAD_LOCAL_INVOICE;
  static CUSTOMER_UN_AUTH_INVOICE = environment.ADMIN_SERVICE.CUSTOMER.UN_AUTH_INVOICE;

  static CUSTOMER_ALL_CREDIT_NOTES= environment.ADMIN_SERVICE.CUSTOMER.ALL_CREDIT_NOTE;
  static CUSTOMER_SAVE_CREDIT_NOTE = environment.ADMIN_SERVICE.CUSTOMER.SAVE_CREDIT_NOTE;
  static CUSTOMER_LOAD_SELECTED_CREDIT_NOTE = environment.ADMIN_SERVICE.CUSTOMER.LOAD_CREDIT_NOTE;
  static CUSTOMER_CUSTOMER_INVOICES_LIST = environment.ADMIN_SERVICE.CUSTOMER.LOAD_CUSTOMER_INVOICE_LIST;
  static CUSTOMER_CUSTOMER_INVOICES_ITEMS__LIST = environment.ADMIN_SERVICE.CUSTOMER.LOAD_CUSTOMER_INVOICE_ITEMS_LIST;
  static CUSTOMER_CANCEL_CREDIT_NOTE = environment.ADMIN_SERVICE.CUSTOMER.CANCEL_CREDIT_NOTE;

  /*CUSTOMER MODULE APIS END*/

  /*VENDOR MODULE APIS START*/
  static VENDOR_GET_VEN_TABLE_DATA = environment.ADMIN_SERVICE.VENDOR.GET_VEN_TABLE_DATA;
  static VENDOR_SAVE_VEN_DATA = environment.ADMIN_SERVICE.VENDOR.SAVE_VEN_DATA;
  static VENDOR_SAVE_VEN_OTHER_DATA = environment.ADMIN_SERVICE.VENDOR.SAVE_VEN_OTHER_DATA;
  static VENDOR_LOAD_SELECTED_VEN_DATA = environment.ADMIN_SERVICE.VENDOR.LOAD_SELECTED_VEN_DATA;
  static VENDOR_LOAD_SELECTED_OTHER_VEN_DATA = environment.ADMIN_SERVICE.VENDOR.LOAD_SELECTED_OTHER_VEN_DATA;
  static VENDOR_LOAD_ALL_VENDOR_CREDITS = environment.ADMIN_SERVICE.VENDOR.LOAD_ALL_VENDOR_CREDITS;
  static VENDOR_LOAD_VENDOR_PO = environment.ADMIN_SERVICE.VENDOR.LOAD_ALL_VENDOR_PO;
  static VENDOR_LOAD_VENDOR_PO_ITEMS = environment.ADMIN_SERVICE.VENDOR.LOAD_ALL_VENDOR_PO_ITEMS;
  static VENDOR_SAVE_VENDOR_CREDIT = environment.ADMIN_SERVICE.VENDOR.SAVE_VENDOR_CREDIT;
  static VENDOR_LOAD_SELECTED_VENDOR_CREDIT = environment.ADMIN_SERVICE.VENDOR.LOAD_SELECTED_VENDOR_CREDIT;
  static VENDOR_CANCEL_VENDOR_CREDIT = environment.ADMIN_SERVICE.VENDOR.CANCEL_VENDOR_CREDIT;
  static VENDOR_RESET_VENDOR_CREDIT = environment.ADMIN_SERVICE.VENDOR.RESET_VENDOR_CREDIT;

  /*VENDOR MODULE APIS END*/

  /*INVENTORY MODULE APIS START*/
  static INVENTORY_GET_DES_TABLE_DATA = environment.ADMIN_SERVICE.INVENTORY.GET_VEN_TABLE_DATA;
  static INVENTORY_GET_DIS_PRINT_JASPER = environment.ADMIN_SERVICE.INVENTORY.GET_DIS_PRINT_JASPER;
  static INVENTORY_GET_GRN_PRINT_JASPER = environment.ADMIN_SERVICE.INVENTORY.GET_GRN_PRINT_JASPER;
  static INVENTORY_GET_GRN_IMT_PRINT_JASPER = environment.ADMIN_SERVICE.INVENTORY.GET_GRN_IMT_PRINT_JASPER;
  static INVENTORY_GET_GRN_GRN_PRINT_JASPER = environment.ADMIN_SERVICE.INVENTORY.GET_GRN_GRN_PRINT_JASPER;
  static INVENTORY_GET_SELECTED_OD = environment.ADMIN_SERVICE.INVENTORY.GET_SELECTED_OD;
  static INVENTORY_GET_LOCAL_INVOICE_OD = environment.ADMIN_SERVICE.INVENTORY.GET_LOCAL_INVOICE_OD;
  static INVENTORY_SAVE_NEW_DISPATCH = environment.ADMIN_SERVICE.INVENTORY.SAVE_NEW_DISPATCH;
  static INVENTORY_GET_BEAN_BIN = environment.ADMIN_SERVICE.INVENTORY.GET_BEAN_BIN;
  static INVENTORY_GET_DISPATCH_NOTE = environment.ADMIN_SERVICE.INVENTORY.GET_DISPATCH_NOTE;
  static INVENTORY_LOAD_STOCK = environment.ADMIN_SERVICE.INVENTORY.LOAD_STOCK;
  static INVENTORY_UNAUTH_LOCAL_ORDER_DISPATCH = environment.ADMIN_SERVICE.INVENTORY.UNAUTH_LOCAL_ORDER_DISPATCH;
  static INVENTORY_RESTRICT_PRINT = environment.ADMIN_SERVICE.INVENTORY.RESTRICT_PRINT;
  static INVENTORY_GET_GRN_TABLE = environment.ADMIN_SERVICE.INVENTORY.GET_GRN_TABLE;
  static INVENTORY_SAVE_GRN = environment.ADMIN_SERVICE.INVENTORY.SAVE_GRN;
  static INVENTORY_LOAD_SELECTED_GRN = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_GRN;
  static INVENTORY_CANCEL_CRN_GRN = environment.ADMIN_SERVICE.INVENTORY.CANCEL_CRN_GRN;
  static INVENTORY_CANCEL_GRN = environment.ADMIN_SERVICE.INVENTORY.CANCEL_GRN;
  static INVENTORY_QC_CHECK_GRN = environment.ADMIN_SERVICE.INVENTORY.QC_CHECK_GRN;
  static INVENTORY_SAVE_GRN_CRN = environment.ADMIN_SERVICE.INVENTORY.SAVE_GRN_CRN;
  static INVENTORY_SAVE_GRN_IMT = environment.ADMIN_SERVICE.INVENTORY.SAVE_GRN_IMT;
  static INVENTORY_LOAD_SELECTED_GRN_PO = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_GRN_PO;
  static INVENTORY_LOAD_SELECTED_CRN_FOR_GRN = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_CRN_FOR_GRN;
  static INVENTORY_LOAD_SELECTED_CRN_FOR_GRN2 = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_CRN_FOR_GRN2;
  static INVENTORY_LOAD_SELECTED_IMT_FOR_GRN = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_IMT_FOR_GRN;
  static INVENTORY_LOAD_SELECTED_IMT_FOR_GRN2 = environment.ADMIN_SERVICE.INVENTORY.LOAD_SELECTED_IMT_FOR_GRN2;
  static INVENTORY_LOAD_ALL_PO = environment.ADMIN_SERVICE.INVENTORY.LOAD_ALL_PO;
  static INVENTORY_LIST_CRN_FOR_GRN = environment.ADMIN_SERVICE.INVENTORY.LIST_CRN_FOR_GRN;
  static INVENTORY_LIST_IMT = environment.ADMIN_SERVICE.INVENTORY.LIST_IMT;
  /*INVENTORY MODULE APIS END*/

  /*PURCHASING MODULE APIS START*/
  static PURCHASING_GET_ALL_PRN = environment.ADMIN_SERVICE.PURCHASING.GET_ALL_PRN;
  static PURCHASING_GET_ALL_PRN_WITHOUT_PAGE = environment.ADMIN_SERVICE.PURCHASING.GET_ALL_PRN_WITHOUT_PAGE;
  static PURCHASING_GET_ALL_PRN_WITH_SORT = environment.ADMIN_SERVICE.PURCHASING.GET_ALL_PRN_WITH_SORT;
  static PURCHASING_GET_ALL_PRN_WITH_SEARCH_TERM = environment.ADMIN_SERVICE.PURCHASING.GET_ALL_PRN_WITH_SEARCH_TERM;
  static PURCHASING_GET_SELECTED_PRN = environment.ADMIN_SERVICE.PURCHASING.GET_SELECTED_PRN;
  static PURCHASING_GET_ITEM_STORED_DATA = environment.ADMIN_SERVICE.PURCHASING.GET_ITEM_STORED_DATA;
  static PURCHASING_GET_ITEM_STORED_DATA_ITEM = environment.ADMIN_SERVICE.PURCHASING.GET_ITEM_STORED_DATA_ITEM;
  static PURCHASING_SAVE_PRN = environment.ADMIN_SERVICE.PURCHASING.SAVE_PRN;
  static PURCHASING_CANCEL_PRN = environment.ADMIN_SERVICE.PURCHASING.CANCEL_PRN;
  //purchaseOrder
  static PURCHASING_ALL_PURCHASE_ORDER = environment.ADMIN_SERVICE.PURCHASING.ALL_PURCHASE_ORDER;
  static PURCHASING_ALL_PRN = environment.ADMIN_SERVICE.PURCHASING.ALL_PRN;
  static PURCHASING_LOAD_SELECTED_PO = environment.ADMIN_SERVICE.PURCHASING.LOAD_PO;
  static PURCHASING_LOAD_SELECTED_PO_FOR_POPUP = environment.ADMIN_SERVICE.PURCHASING.LOAD_PO_FOR_POPUP;
  static PURCHASING_LOAD_SELECTED_PRN = environment.ADMIN_SERVICE.PURCHASING.LOAD_PRN;
  static PURCHASING_SAVE_PO = environment.ADMIN_SERVICE.PURCHASING.SAVE_PO;
  static PURCHASING_CLOSE_PO = environment.ADMIN_SERVICE.PURCHASING.CLOSE_PO;
  static PURCHASING_UNAUTH_PO = environment.ADMIN_SERVICE.PURCHASING.UNAUTH_PO;
  static PURCHASING_GET_GEN_TERMS = environment.ADMIN_SERVICE.PURCHASING.GET_GEN_TERMS;
  static PURCHASING_RESET_PRINT_COUNT = environment.ADMIN_SERVICE.PURCHASING.RESET_PRINT_COUNT;
  /*PURCHASING MODULE APIS END*/

  /*COMMON MODULE APIS START*/
  static COMMON_LOAD_SELECTED_ENTRY = environment.ADMIN_SERVICE.COMMON.LOAD_SELECTED_ENTRY;
  static COMMON_LOAD_CURRENCY = environment.ADMIN_SERVICE.COMMON.LOAD_CURRENCY;
  static COMMON_LOAD_JOU_TYPES = environment.ADMIN_SERVICE.COMMON.LOAD_JOU_TYPES;
  static COMMON_LOAD_LEDGERS = environment.ADMIN_SERVICE.COMMON.LOAD_LEDGERS;
  static COMMON_LOAD_LEDGERS_CAO = environment.ADMIN_SERVICE.COMMON.LOAD_LEDGERS_CAO;
  static COMMON_LOAD_LEDGERS_TWO = environment.ADMIN_SERVICE.COMMON.LOAD_LEDGERS_TWO;
  static COMMON_LOAD_PLANTS = environment.ADMIN_SERVICE.COMMON.LOAD_PLANTS;
  static COMMON_LOAD_SHIPMENTS = environment.ADMIN_SERVICE.COMMON.LOAD_SHIPMENTS;
  static COMMON_LOAD_VENDORS = environment.ADMIN_SERVICE.COMMON.LOAD_VENDORS;
  static COMMON_LOAD_CATEGORIES = environment.ADMIN_SERVICE.COMMON.LOAD_CATEGORIES;
  static COMMON_LOAD_COUNTRIES = environment.ADMIN_SERVICE.COMMON.LOAD_COUNTRIES;
  static COMMON_GET_REGION_NUMBER = environment.ADMIN_SERVICE.COMMON.GET_REGION_NUMBER;
  static COMMON_GET_EMPLOYEE_LIST = environment.ADMIN_SERVICE.COMMON.GET_EMPLOYEE_LIST;
  static COMMON_GET_REGION_LIST = environment.ADMIN_SERVICE.COMMON.GET_REGION_LIST;
  static COMMON_GET_LEDGER_LIST = environment.ADMIN_SERVICE.COMMON.GET_LEDGER_LIST;
  static COMMON_GET_LOCAL_INVOICE = environment.ADMIN_SERVICE.COMMON.GET_LOCAL_INVOICE;
  static COMMON_GET_EMAIL_GROUPS = environment.ADMIN_SERVICE.COMMON.GET_EMAIL_GROUPS;
  static COMMON_SEND_EMAIL = environment.ADMIN_SERVICE.COMMON.SEND_EMAIL;
  static COMMON_GET_PUR_REQ_PDFL = environment.ADMIN_SERVICE.COMMON.GET_PUR_REQ_PDF;
  static COMMON_GET_DEPARTMENTS = environment.ADMIN_SERVICE.COMMON.GET_DEPARTMENTS;
  static COMMON_GET_CERTIFICATIONS = environment.ADMIN_SERVICE.COMMON.GET_CERTIFICATIONS;
  static COMMON_GET_FINANCIAL_YEARS = environment.ADMIN_SERVICE.COMMON.GET_FINANCIAL_YEARS;
  static COMMON_GET_FINANCIAL_YEAR_DETAILS = environment.ADMIN_SERVICE.COMMON.GET_FINANCIAL_YEAR_DETAILS;
  static COMMON_GET_NOTIFICATIONS = environment.ADMIN_SERVICE.COMMON.GET_NOTIFICATIONS;
  static COMMON_GET_PROVIDER_BANK = environment.ADMIN_SERVICE.COMMON.GET_PROVIDER_BANK;
  static COMMON_GET_ACTIVE_DATES = environment.ADMIN_SERVICE.COMMON.GET_ACTIVE_DATES;
  static COMMON_GET_SUP_CUS_CATEGORY = environment.ADMIN_SERVICE.COMMON.GET_SUP_CUS_CATEGORY;
  static COMMON_GET_LOAN_TYPES = environment.ADMIN_SERVICE.COMMON.GET_LOAN_TYPES;
  static COMMON_GET_LIST_ACCOUNTS =  environment.ADMIN_SERVICE.COMMON.LIST_ACCOUNTS;
  static COMMON_LOAD_CERTIFICATE_LIST =  environment.ADMIN_SERVICE.COMMON.LIST_CERTIFICATES;
  static COMMON_LOAD_SUP_CUS_LIST =  environment.ADMIN_SERVICE.COMMON.SUP_CUS_LIST;
  static COMMON_LOAD_ITEM_LIST =  environment.ADMIN_SERVICE.COMMON.ITEMS_LIST;
  static COMMON_LOAD_PRO_LIST =  environment.ADMIN_SERVICE.COMMON.GET_PROJECT_LIST;
  static COMMON_LOAD_EX_RATE = environment.ADMIN_SERVICE.COMMON.GET_EX_RATE;
  static COMMON_CLOSE_FINANCE_YEAR = environment.ADMIN_SERVICE.COMMON.CLOSE_FINANCE_YEAR;

  /*COMMON MODULE APIS END*/

  /*REPORT MODULE APIS START*/
  static REPORT_LOAD_TRIAL_BALANCE = environment.ADMIN_SERVICE.REPORT.LOAD_TRIAL_BALANCE;
  static REPORT_LOAD_LEDGER_REPORT = environment.ADMIN_SERVICE.REPORT.LOAD_LEDGER_REPORT;
  static REPORT_LOAD_GENERAL_LEDGER = environment.ADMIN_SERVICE.REPORT.LOAD_GENERAL_LEDGER;
  static REPORT_LOAD_LOAN_REPORT = environment.ADMIN_SERVICE.REPORT.LOAD_LOAN_REPORT;
  static REPORT_LOAD_PNL = environment.ADMIN_SERVICE.REPORT.LOAD_PNL;
  static REPORT_LOAD_GP = environment.ADMIN_SERVICE.REPORT.LOAD_GP;
  static REPORT_LOAD_BALANCE_SHEET = environment.ADMIN_SERVICE.REPORT.LOAD_BALANCE_SHEET;
  static REPORT_LOAD_SELECTED_BALANCE_SHEET = environment.ADMIN_SERVICE.REPORT.LOAD_SELECTED_BALANCE_SHEET;
  static REPORT_LOAD_SUP_CUS_AGAIN = environment.ADMIN_SERVICE.REPORT.LOAD_SUP_CUS_AGAIN;
  static REPORT_LOAD_SUP_CUS_TRANSACTION = environment.ADMIN_SERVICE.REPORT.LOAD_SUP_CUS_TRANSACTION;
  static REPORT_LOAD_CUS_OUTSTANDING = environment.ADMIN_SERVICE.REPORT.LOAD_CUS_OUTSTANDING;
  static REPORT_LOAD_VEN_OUTSTANDING = environment.ADMIN_SERVICE.REPORT.LOAD_VEN_OUTSTANDING;
  static REPORT_LOAD_RECEIVED_MONEY_DETAILS = environment.ADMIN_SERVICE.REPORT.LOAD_RECEIVED_MONEY_DETAILS;
  static REPORT_LOAD_VENDOR_CREDIT_SUMMERY = environment.ADMIN_SERVICE.REPORT.LOAD_VENDOR_CREDIT_SUMMERY;
  static REPORT_LOAD_PAYMENT_DETAILS = environment.ADMIN_SERVICE.REPORT.LOAD_PAYMENT_DETAILS;
  static REPORT_LOAD_PNL_DETAILS = environment.ADMIN_SERVICE.REPORT.LOAD_PNL_DETAILS;
  /*REPORT MODULE APIS END*/

  static getDefaultHeaders(): HttpHeaders {
    const headers = new HttpHeaders({'Content-type': 'application/json; charset=utf-8'});
    return headers;
  }
}
